[package]
name = "midi2mml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termination = "0.1.2"
midly = "0.5"
